name: Docker Publish

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for your job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest tag and build Docker images
        run: |
          repoName="wocoio"
          service="cloud-iam-manager"
          
          # Get the latest tag for the service from Docker Hub
          latest_tag=$(docker pull ${repoName}/${service}:latest > /dev/null 2>&1; \
            docker images --format "{{.Tag}}" ${repoName}/${service} | sort -rV | head -n 1)
          
          # If no tag exists, start from the default version
          if [ -z "$latest_tag" ]; then
            latest_tag="1.0.0"
          fi
          
          # Increment the tag version
          major=$(echo $latest_tag | cut -d '.' -f 1)
          minor=$(echo $latest_tag | cut -d '.' -f 2)
          service_new_tag="${major}.$((minor+1)).0"
          
          echo "Service new tag: $service_new_tag"
          
          # Build and push the Docker image
          docker build -t ${repoName}/${service}:${service_new_tag} .
          docker push ${repoName}/${service}:${service_new_tag}
